### ISSUE TITLE
error in 3.5.1: Ember.Object.create no longer supports defining computed properties

### ISSUE THREAD

**Issue by BryanCrotaz** [offirgolan/ember-time-machine#138]
in `utils/value.js`

error above is thrown when `Machine.create(` is called.

I've tried `Machine.extend(params).create()` but then I get an infinite recursion. Any thoughts as to how to fix this?

In this case the time machine object is the root of a tree of Ember Data models.

**Comment by BryanCrotaz** [comment]
@allthesignals I've tried using your PR but it has the same issue.

**Comment by offirgolan** [comment]
Can you share some example code of what exactly you're trying to do? It sounds like you're trying to set a CP on an object instance instead of using `defineProperty`.

**Comment by BryanCrotaz** [comment]
Well that's embarrassing - found exactly that down deep in the object hierarchy.
