### ISSUE TITLE
How to use time-machine with Ember-data

### ISSUE THREAD

**Issue by henderikus** [offirgolan/ember-time-machine#17]
Hi,

I want to use Ember-Time-Machine on all of my models, so I can rollback user changes with '''undoAll''.  Is there any documentation about how to use TM with EmberData models.

My first attempt was to reopen the 'DS.Store.' and wrap TimeMachine around the 'findRecord' function like this:

'''
  DS.Store.reopen({
    findRecord() {
      let record=this._super(...arguments);
      return TimeMachine.Object.create({content: record});
    }
'''

But this (ofcourse) doensn't work, because the TimeMachine object is not the same as what 'findRecord' returns normally :-)

**Comment by offirgolan** [comment]
@henderikus the example in the demo uses TM + ED. Unfortunately, I dont believe what you are trying to do is possible nor best practice. I suggest the following:

```js
import Ember from 'ember';
import TimeMachine from 'ember-time-machine';

export default Ember.Route.extend({
  model() {
    return this.store.findRecord('user', 1);
  },

  setupController(controller, model) {
    controller.set('model', TimeMachine.Object.create({
      content: model
   }));
  }
});
```

Once you have a TM set for a single model, all child models will be tracked as well.

**Comment by offirgolan** [comment]
@henderikus Im gonna go ahead and close this one, feel free to reopen if you need some more help.
