### ISSUE TITLE
Relationship syntax is inconsistent with ember-data

### ISSUE THREAD

**Issue by AndyPyeSC** [offirgolan/ember-time-machine#23]
Thanks for the addon, it seems to work really well! However while playing around with it this morning I came across a stumbling point whilst trying to make undoable updates on a `hasMany` relationship.

Initially I wrote my code treating the relationship as async, as I would expect to with a normal model:

    posts.get("comments")
        .then(comments => comments.pushObject(comment));

However, I got the error `posts.get(...).then is not a function`. I found that updating the code to treat the relationship as synchronous,

    posts.get("comments").pushObject(comment);

made it work, with undoAll then rolling back additions/removals on the `comments` relationship as hoped.

It would be useful if `ember-time-machine` treated relationships in a way that was consistent with `ember-data`, so that introducing the addon to an existing project doesn't require code changes. It also concerns me as to how async relationships are being treated - if a relationship is lazy-loaded and the data has not yet been fetched from the server, will using the synchronous access I had to resort to cause problems?

**Comment by offirgolan** [comment]
Im assuming posts is a time machine.

When you do `posts.get('comments')` it returns a new time machine wrapped around `comments` which wont have a `.then`. What you can do instead is:

```js
const comments = posts.get('comments');
posts.get('comments').invoke('then', (result) => comments.pushObject(result));

// OK

comments.get('content').then(/* blah blah blah */);
```

Let me know if that works out okay for you!

**Comment by AndyPyeSC** [comment]
Thanks for getting back so quickly! `posts` (should've been `post`, oops) is indeed a time machine.

I'm a little confused by your first suggestion - I'm not familiar with the `invoke` method, but I'd expect `result` to be the `comments` relationship, rather than the `comment` I want to push into that relationship.

The second suggestion returns a promise, but again necessitates a difference between looking up a relationship on a plain model vs. a time machine wrapped model. To me, ideally, there would be no difference syntactically between the two, i.e. you would be able to access relationships on time machine models exactly the same way as with plain ember data models. Maybe that isn't possible/valuable though.

In my use case I ended up preloading the relationship for other reasons, which allows me to just continue using the synchronous `posts.get("comments").pushObject(comment)` approach.

**Comment by AndyPyeSC** [comment]
Thank you for the explanation! What you're saying makes perfect sense, and in the end, having to occasionally `.invoke` or `.get("content")` is a small price to pay for the excellent functionality your addon offers :smiley: Closing the issue.

**Comment by AndyPyeSC** [comment]
Unfortunately I'm back to reopen this! I've just found that if I use the `post.get("comments.content").then(comments => comments.pushObject(comment))` suggestion you gave me earlier, rolling back via `post.undoAll()` does not remove `comment` from the `comments` relationship. If I use the synchronous-style `post.get("comments").pushObject(comment)`, the relationship gets rolled back correctly.

**Comment by offirgolan** [comment]
@AndyPyeSC thats because you're now only interacting with the actual model and no long with the comments time machine. 

Try something like this instead:

```js
const comments = posts.get('comments'); // Reference to our comments time machine
comments.invoke('then', (result) => comments.pushObject(result)); // Call pushObject on the comments TM
```

**Comment by AndyPyeSC** [comment]
I've had a play with the `.invoke(...)` approach and wasn't able to get anything working. However, looking at the documentation for `invoke` I figured I could do this:

    const comments = post.get("comments");
    comments.get("content").then((/* commentsContent */) => {
        comments.pushObject(comment);
    });

I then realised that this is exactly what you were suggesting originally, except I made the mistake then of pushing `comment` into the non-time machine `commentsContent` array, instead of the time machine `comments` array. Should've thought it through better to start with... thanks for clearing that up though! :smiley:

**Comment by offirgolan** [comment]
> I then realised that this is exactly what you were suggesting originally, except I made the mistake then of pushing comment into the non-time machine commentsContent array, instead of the time machine comments

Glad we are finally on the same page 😺 ! Weird that invoke didnt work out... Ill need to take a look into that and see whats going on there.
