### ISSUE TITLE
Issue with Date format.

### ISSUE THREAD

**Issue by henderikus** [offirgolan/ember-time-machine#24]
Hello Offirgolan

We are using Ember-TimeMachine for rollback models with relationships, because Ember rollbackAttributes is lacking rollback of relationship id's.  This works very very nice :+1: 

But I have an issue with accessing fields from a model in a template, which are of datatype Date. They are returning empty strings.

Strings I can access as  '''model.stringfield''', while date fields needs explicity be accessed with '''model.content.datefield''', otherwise TM will return an empty string(model.datefield).

I think '''model.datefield'' should return an Date Object instead of an empty string...

Is this a missing feature or am I doing something terrible wrong again? :)

Cheers!

**Comment by offirgolan** [comment]
This is definitely a bug. Let me investigate this further and see whats going on here.

**Comment by offirgolan** [comment]
@henderikus fixed with `v0.0.2`! Thanks for bringing this to my attention 😺

**Comment by henderikus** [comment]
You too for the quick fix! 
:-)
