### ISSUE TITLE
Working with ember-cp-validations

### ISSUE THREAD

**Issue by angelomachado** [offirgolan/ember-time-machine#84]
Thanks for this great addon. I was wondering how can i get it to work with ember-cp-validations.

Not sure if something like this would work

```javascript
//app/routes/application.js
  model() {
    const timeMachine = TimeMachine.Object.create({ 
      content: this.store.createRecord('user')
    });
    return timeMachine;
  },
```

```
{{!-- app/templates/application.hbs --}}
   {{validated-input
    model=model
    valuePath='name'
  }}
```

```javascript
//app/models/user.js
import Model from 'ember-data/model';
import attr from 'ember-data/attr';
import { UserValidations } from '../validators/user-validator';

export default Model.extend(UserValidations, {
  name: attr('string'),
  email: attr('string'),
  password: attr('string'),
  passwordConfirmation: attr('string')
});
```

**Comment by offirgolan** [comment]
@angelomachado are you running into a specific issue?

**Comment by angelomachado** [comment]
I am pretty sure i am missing something. My validated-input component works well with an ember data model object or even with a component. When i use the code above passing the timeMachine object it does not.  Should it work out of the box? Thank you again!

**Comment by offirgolan** [comment]
@angelomachado it should work out of the box! Im not really sure why it isnt. If you can replicate this issue in a dummy app and link me to it, I can debug whats going on. 

What exactly are you trying to do here? Are you getting any error messages? Are you attempting to do `undoAll`?

**Comment by angelomachado** [comment]
Just realized that i had to pass the timeMachine content property to my validated-input. Sorry for your time!

**Comment by offirgolan** [comment]
Haha no problem! Glad you were able to solve it 😺
