### ISSUE TITLE
Wrap hasMany records by time-machine

### ISSUE THREAD

**Issue by pleszkowicz** [offirgolan/ember-time-machine#87]
Thanks for your work on this addon. This is what we're looking for!
I went through the setup and I'm able to undo changes on the route model and `hasmany` property. But`hasMany` records are not wrapped by time-machine. I'm looking for a way to undo changes done on such records. 
@offirgolan can you please give me some idea, where/how it should be done?

**Comment by offirgolan** [comment]
@pleszkowicz thats odd. This should work out of the box (at least from what I've tested). If you take a look at the demo app, it also uses hasMany relationships and they get wrapped in a TimeMachine. Is there any chance you can create a dummy app to replicate this behavior or give me some replication steps?

**Comment by pleszkowicz** [comment]
@offirgolan yeah, I can confirm that it works in your demo app.
I can't simply reproduce the issue, we use JSONAPIAdapter.
Data is fetched from the server (no mirage)
We overrode `normalize()` method in the serializer of the main model, and also we use there `resourceHash.links` for hasMany relationships.
But IMHO, it shouldn't affect. Here is a logged `model.get('hasManyProp')` of our app.
<img width="469" alt="screen shot 2016-10-09 at 18 04 19" src="https://cloud.githubusercontent.com/assets/5617996/19220982/efc80c16-8e4a-11e6-9ca9-d3aea4b3c71b.png">
Hope it will be useful.

**Comment by offirgolan** [comment]
@pleszkowicz how are you accessing records on the `hasManyProp` array?

Have you tried `model.get('hasManyProp').objectAt(0)`?

**Comment by pleszkowicz** [comment]
@offirgolan I just console logged `model.get('hasManyProp').objectAt(0)`.
The hasMany record is also wrapped by time-machine. Hence it looks like some internal issue in our app.
Thanks for your help! I'll investigate.

**Comment by pleszkowicz** [comment]
@offirgolan I passed `model.hasMany.content` inside the template, which was causing the issue. Changes were done directly on the record, instead of time-machine.
Thanks for quick responses. Please mark issue as solved.

**Comment by offirgolan** [comment]
@pleszkowicz no worries! Glad to help! 😸

**Comment by LucasSys** [comment]
hello, sorry for bother

it is possible to include a hasMany that is within a relationship belongs to the model that is the time machine?
